### ISSUE TITLE
rename player.rb to player_ship.rb

### ISSUE THREAD

**Issue by rasheedelkassed** [abell95/galaga_invaders#9]
The name of the file is different from the class within.

**Comment by bmchristensen** [comment]
Specificity in class name is potentially restrictive. If this class was extended or inherited by another, the name would be misleading since the player does not control any other actors in the system. Specificity is important, but probably not at the cost of flexibility and tolerance to change. I propose that the player.rb aka player_ship.rb be renamed to ship.rb.
